### ISSUE TITLE
crafting which i guess is not supposed to happen

### ISSUE THREAD

**Issue by quietss** [kyber-6/fantasymc-fabric-modpack#32] opened 2023-08-20 20:10 UTC
### Describe the bug

i wanted to make an iron sword but something went.. wrong?

### Reproduction Steps

i dont know what is it for sorry

### Screenshots

![image](https://github.com/kyber-6/fantasymc-fabric-modpack/assets/142751006/226f0ded-ce13-4286-a147-0e1372111220)

### Mod pack version

v14.5

**Comment by quietss** [comment] 2023-08-20 20:12
also if some dev see this as you can see theres is no recipe book in craftng, is this fixable?

**Comment by kyber-6** [comment] 2023-08-25 02:44
Duplicate of https://github.com/kyber-6/fantasymc-fabric-modpack/issues/29.

The recipe book is disabled as the [REI](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items) mod is installed.

**Closed by kyber-6** 2023-08-25 02:44 UTC
Labels: bug
